### ISSUE TITLE
[REQUEST] - Example for RESTful HTTP example

### ISSUE THREAD

**Issue by sujit-baniya** [shaovie/goev#7]
This is great library. Can you add some RESTful HTTP example with some middlewares

**Comment by shaovie** [comment]
Hello, currently Goev is positioned as an underlying TCP development framework and has no plans to upgrade it to a web framework,

> This is great library. Can you add some RESTful HTTP example with some middlewares

**Comment by sujit-baniya** [comment]
Would you also support for macOS or Windows?

**Comment by shaovie** [comment]
Sorry, it will never support Windows. I don't think it's necessary. MacOs, maybe it will. I also develop on MacBook, but I only compile on it and don't conduct actual running tests. I'll have time to implement kqueue when I have time
